version: '3.8'

services:

  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT

  mission-request-service:
    depends_on:
      - postgresdb
    build: 
      context: .
      args:
        - JAR_FILE=target/mission-request-service-0.0.1-SNAPSHOT.jar
    restart: on-failure
    env_file: ./.env
    ports:
      - $MISSION_REQUEST_SERVICE_LOCAL_PORT:$MISSION_REQUEST_SERVICE_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
          "spring.datasource.username": "$POSTGRESDB_USER",
          "spring.datasource.password": "$POSTGRESDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  
volumes:
  db:

    